name: Manual Release Please

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install release-please v16.16.2
        run: npm install -g release-please@16.16.2

      - name: Run release-please manually
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PR_TOKEN }}
        run: |
          release-please release-pr \
            --token="${GITHUB_TOKEN}" \
            --repo-url="${{ github.repository }}" \
            --release-type=python \
            --default-branch=main
